import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/ui/Container";
import Navbar from './../components/layout/Navbar';
import Footer from "@/components/layout/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Shoppy - Mini E commerce brand",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans tracking-tight bg-red-500`}
      >
        <Navbar/>
        <Container>{children}</Container>
        <Footer/>
      </body>
    </html>
  );
}
